# This is a basic workflow to help you get started with Actions

name: My first workflow

# Controls when the workflow will run
on: [push]
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
