name: Call Reusable Workflow

on:
  push:
    branches: [ main ]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      username: "octocat"
      environment: "production"
    secrets:
      API_KEY: ${{ secrets.MY_API_KEY }}
